### ISSUE TITLE
CDS data update broke our pipeline yesterday.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#48]
It looks like this was a transient issue.  If I download the latest CDS data, then our pipeline works.  But we may want to look into what went wrong and if we should have better error handling in our own code or something.

1. `git checkout 18ff6a9` in your covid-data-public repo.
2. Run `python validate.py -d ~/src/covid-data-public` in covid-data-model repo.

Result: 
```
run.py failed with code 1
INFO:libs.CovidDatasets:NO COUNTY DATA: 2020-03-12 00:00:00
INFO:libs.CovidDatasets:NO COUNTY DATA: 2020-03-04 00:00:00
...
INFO:libs.CovidDatasets:NO COUNTY DATA: 2020-03-04 00:00:00
INFO:libs.CovidDatasets:NO COUNTY DATA: 2020-03-03 00:00:00
Traceback (most recent call last):
  File "/Users/mikelehen/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 84, in <module>
    model_state('USA', state, intervention),
  File "run.py", line 56, in model_state
    'timeseries': Dataset.get_timeseries_by_country_state(country, state, MODEL_INTERVAL),
  File "/Users/mikelehen/tmp/covid-data-model/libs/CovidDatasets.py", line 205, in get_timeseries_by_country_state
    return self.prep_data(self.combine_state_county_data(country, state), model_interval)
  File "/Users/mikelehen/tmp/covid-data-model/libs/CovidDatasets.py", line 148, in prep_data
    return self.backfill(self.cutoff(series), model_interval)
  File "/Users/mikelehen/tmp/covid-data-model/libs/CovidDatasets.py", line 137, in backfill
    self.backfill_to_init_date(series, model_interval),
  File "/Users/mikelehen/tmp/covid-data-model/libs/CovidDatasets.py", line 93, in backfill_to_init_date
    min_interval_row = interval_rows[interval_rows[self.DATE_FIELD] == interval_rows[self.DATE_FIELD].min()].iloc[0]
  File "/Users/mikelehen/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mikelehen/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'
```

**Comment by ghop02** [comment]
Found the error:

This only happens when you specify a `filter_past_date` for the dataset that is earlier than the earliest record.  In this case, it happens with virginia with a filter past date less than 3/22.
Happens [here](https://github.com/covid-projections/covid-data-model/blob/master/libs/CovidDatasets.py#L86-L89): 
```python

    def backfill_to_init_date(self, series, model_interval):
        series = series.sort_values(self.DATE_FIELD).reset_index(drop=True)  # Sort the series by the date of the record
        # Problem happens here: Since there is no data, it returns an empty dataframe
        # then when trying to access the date column later down the line, it errors
        data_rows = series[series[self.CASE_FIELD] > 0]  # Find those rows that actually have reported cases
        interval_rows = data_rows[data_rows[self.DATE_FIELD].apply(
            lambda d: (d - self._START_DATE).days % model_interval == 0
        )]
```

Simple fix to this problem: run the dataset without filter_past_date.
Also, if we could figure out a way to filter the data after doing the data prep, would also fix it

**Comment by davidstrauss** [comment]
`filter_past_date` was primarily intended to allow re-running forecasts without having them drift as new data came in, but this need is better-served now by (the not-yet added but intended) ability to pin the data source to a single commit in our data repo.

**Comment by davidstrauss** [comment]
Posted issue #50 to address this more comprehensively.

**Comment by davidstrauss** [comment]
We now isolate runtime operations from the latest data published by a source, allowing us to isolate (or even roll back) breakage from a source.

We don't auto-test source updates against our data source libraries. So, feel free to re-open if you think this isn't adequately addressed. I'm planning to leave #50 open, though.
